### ISSUE TITLE
Page Tree not visible

### ISSUE THREAD

**Issue by evolvedn2dwt** [WikiTransformationProject/wikitraccs-wikipakk-releases#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We're seeing a lot of latency in opening the Page Tree, with items not loading - is there a capacity limit/concurrent user limit?  This issue resulted in us not being able to use the page tree editor because the tree view would not expand. I tried several fixes with no luck. Removed add and added it back, clear cache, tried different browsers, etc.

### Expected Behavior

Page tree and page tree editor to function as it did before...

### WikiTraccs Version

WikiPakk 2.3.4

### Confluence Version

Confluence 7 (7.18 or newer)

### Confluence Data Center?

- [ ] This is about Confluence Data Center

### Anything else?

![wikipakk1](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/150864573/b0a9436e-914f-48c6-ba69-2aa465cf8d63)

**Comment by heinrich-ulbricht** [comment]
@evolvedn2dwt Could you please try upgrading to the latest version 2.4.0.5 which contains a heap of optimizations regarding render performance.

Can you confirm that the "too many item IDs" error happens when a parent node has more than 100 child nodes? If yes, could you briefly describe when this error happens? Is it when opening the tree panel for the first time, or when expanding the children of a page? Please test this with the latest version. You can confirm that you are on the latest version by clicking on the question mark in the tree view panel - this opens a dialog showing the current version.

Thank you!

**Comment by evolvedn2dwt** [comment]
@heinrich-ulbricht  Definitely, thanks for the fast response. I will get back to you after we have competed the upgrade and more testing.

**Comment by heinrich-ulbricht** [comment]
@evolvedn2dwt I can confirm there is an issue when a page has more than 100 child pages. A fix release is being prepared.

**Comment by heinrich-ulbricht** [comment]
A new release has been submitted to AppSource. It should be available for download within a few days.

**Comment by evolvedn2dwt** [comment]
@heinrich-ulbricht  Thank you! I would hold off upgrading until the new release is available then report back here. Thanks again for the fast responses!

**Comment by evolvedn2dwt** [comment]
@heinrich-ulbricht  We completed the upgrade and it has resolved the issue. The page tree loads MUCH faster now. Thank you!

**Comment by heinrich-ulbricht** [comment]
@evolvedn2dwt Thanks for the feedback! If you like, vote for ideas for future tree features that you'd find useful: [Ideas](https://github.com/WikiTransformationProject/wikitraccs-wikipakk-releases/issues?q=is%3Aissue+is%3Aopen+label%3Aidea).
