### ISSUE TITLE
"Valid License" Message for Site Members

### ISSUE THREAD

**Issue by Oli-UCL** [WikiTransformationProject/wikitraccs-wikipakk-releases#24]
Hi,

Hope you are well.

Members of the SharePoint with the WikiPakk app add-in can access the Page Tree Editor but receive a message that "Could not find a valid license" message (see attached screenshot).
![WikiPakk SP Members Valid License msg](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/170094128/9811da36-108b-4fdb-9bab-c83674b0b9a1)

The members of the Sharepoint site can still use the Page Tree editor (move pages etc.).

The site admins do not receive this message when opening the Page Tree Editor.

Is this as intended?

Or I need to make some changes on our end?

**Comment by heinrich-ulbricht** [comment]
Hi @Oli-UCL,

The easiest way to diagnose this is looking at the WikiPakk license-related logs. They show each action WikiPakk takes with regard to finding the license key.

Here's an article showing how to get to those logs: [What if WikiPakk cannot find the license?](https://www.wikitransformationproject.com/docs/wikipakk-reference/wikipakk-troubleshooting/wikipakk-troubleshooting-license-issues/#what-if-wikipakk-cannot-find-the-license)

Please send the log messages to support@wikitransformationproject.com. I'll have a look.

Reasons might be:
* the users have no access to the site where the license key is stored
* the license key is stored in a single page, but not in another page
* a bug in WikiPakk

Hopefully the log will quickly reveal the root cause.

Thank you!

**Comment by Oli-UCL** [comment]
HI

Managed to fix it, set the license site read access to everyone.
Thanks for your prompt response..

**Comment by heinrich-ulbricht** [comment]
@Oli-UCL Sounds good! Thanks for the feedback.

Note that **guest users** might still be unable to access the license site unless the ["Everyone" claim](https://learn.microsoft.com/en-us/microsoft-365/troubleshoot/access-management/grant-everyone-claim-to-external-users) was used to grant access (instead of "Everyone except external users"). Same goes for access to the SharePoint **tenant app catalog** (to grant access to apps in general) where guests have no access in a default setting.

This is not a WikiPakk-specific topic but one of guest users and SharePoint in general, but I thought I'd mention it.
